capital = "18660"
build_list = [
    {"building_type": "Warehouse", "level": 5, "aid": 30},
    {"building_type": "Granary", "level": 4, "aid": 32},
    {"building_type": "Main Building", "level": 8},
    {"building_type": "Woodcutter", "level": 1},
    {"building_type": "Clay Pit", "level": 1},
    {"building_type": "Iron Mine", "level": 1},
    {"building_type": "Cropland", "level": 1},
    {"building_type": "Woodcutter", "level": 2},
    {"building_type": "Clay Pit", "level": 2},
    {"building_type": "Iron Mine", "level": 2},
    {"building_type": "Cropland", "level": 2},
    {"building_type": "Rally Point", "level": 1, "aid": 39},
    {"building_type": "Main Building", "level": 10},
    {"building_type": "Warehouse", "level": 9},
    {"building_type": "Woodcutter", "level": 3},
    {"building_type": "Clay Pit", "level": 3},
    {"building_type": "Iron Mine", "level": 3},
    {"building_type": "Woodcutter", "level": 4},
    {"building_type": "Clay Pit", "level": 4},
    {"building_type": "Iron Mine", "level": 4},
    {"building_type": "Woodcutter", "level": 5},
    {"building_type": "Clay Pit", "level": 5},
    {"building_type": "Iron Mine", "level": 5},
    {"building_type": "Granary", "level": 7},
    {"building_type": "Cropland", "level": 3},
    {"building_type": "Cropland", "level": 4},
    {"building_type": "Cropland", "level": 5},
    {"building_type": "Grain Mill", "level": 3, "aid": 21},
    {"building_type": "Main Building", "level": 13},
    {"building_type": "Barracks", "level": 5, "aid": 37},
    {"building_type": "Marketplace", "level": 1, "aid": 31},
    {"building_type": "Embassy", "level": 1, "aid": 29},
    {"building_type": "Academy", "level": 5, "aid": 36},
    {"building_type": "Marketplace", "level": 5, "aid": 31},
    {"building_type": "Warehouse", "level": 11},
    {"building_type": "Granary", "level": 8},
    {"building_type": "Grain Mill", "level": 5, "aid": 21},
    {"building_type": "Woodcutter", "level": 6},
    {"building_type": "Clay Pit", "level": 6},
    {"building_type": "Iron Mine", "level": 6},
    {"building_type": "Palisade", "level": 5, "aid": 40},
    {"building_type": "Smithy", "level": 5, "aid": 33},
    {"building_type": "Stable", "level": 5, "aid": 34},
    {"building_type": "Trapper", "level": 2, "aid": 28},

]

capital_build_list = [
    {"building_type": "Woodcutter", "level": 1},
    {"building_type": "Clay Pit", "level": 1},
    {"building_type": "Iron Mine", "level": 1},
    {"building_type": "Warehouse", "level": 5, "aid": 30},
    {"building_type": "Granary", "level": 4, "aid": 32},
    {"building_type": "Main Building", "level": 8},
    {"building_type": "Cropland", "level": 1},
    {"building_type": "Woodcutter", "level": 2},
    {"building_type": "Clay Pit", "level": 2},
    {"building_type": "Iron Mine", "level": 2},
    {"building_type": "Cropland", "level": 2},
    {"building_type": "Rally Point", "level": 1, "aid": 39},
    {"building_type": "Main Building", "level": 10},
    {"building_type": "Warehouse", "level": 9},
    {"building_type": "Granary", "level": 7},
    {"building_type": "Woodcutter", "level": 3},
    {"building_type": "Clay Pit", "level": 3},
    {"building_type": "Iron Mine", "level": 3},
    {"building_type": "Barracks", "level": 5, "aid": 37},
    {"building_type": "Embassy", "level": 1, "aid": 29},
    {"building_type": "Marketplace", "level": 5, "aid": 31},
    {"building_type": "Academy", "level": 5, "aid": 36},
    {"building_type": "Woodcutter", "level": 4},
    {"building_type": "Clay Pit", "level": 4},
    {"building_type": "Iron Mine", "level": 4},
    {"building_type": "Cropland", "level": 3},
    {"building_type": "Main Building", "level": 13},
    {"building_type": "Warehouse", "level": 11},
    {"building_type": "Granary", "level": 8},
    {"building_type": "Woodcutter", "level": 5},
    {"building_type": "Clay Pit", "level": 5},
    {"building_type": "Iron Mine", "level": 5},
    {"building_type": "Cropland", "level": 4},
    {"building_type": "Main Building", "level": 15},
    {"building_type": "Palisade", "level": 5, "aid": 40},
    {"building_type": "Smithy", "level": 5, "aid": 33},
    {"building_type": "Stable", "level": 5, "aid": 34},
    {"building_type": "Academy", "level": 10, "aid": 36},
    {"building_type": "Embassy", "level": 1, "aid": 29},
    {"building_type": "Palace", "level": 10, "aid":  25},
    {"building_type": "Town Hall", "level": 1, "aid":  23},
    {"building_type": "Woodcutter", "level": 6},
    {"building_type": "Clay Pit", "level": 6},
    {"building_type": "Iron Mine", "level": 6},
    {"building_type": "Cropland", "level": 5},
    {"building_type": "Grain Mill", "level": 5, "aid":  21},
    {"building_type": "Woodcutter", "level": 7},
    {"building_type": "Clay Pit", "level": 7},
    {"building_type": "Iron Mine", "level": 7},
    {"building_type": "Main Building", "level": 20},
    {"building_type": "Palisade", "level": 8, "aid": 40},
    {"building_type": "Smithy", "level": 10, "aid": 33},
    {"building_type": "Stable", "level": 10, "aid": 34},
    {"building_type": "Academy", "level": 15, "aid": 36},
    {"building_type": "Barracks", "level": 12, "aid": 37},
    {"building_type": "Woodcutter", "level": 8},
    {"building_type": "Clay Pit", "level": 8},
    {"building_type": "Iron Mine", "level": 8},
    {"building_type": "Stable", "level": 15, "aid": 34},
    {"building_type": "Barracks", "level": 18, "aid": 37},
    {"building_type": "Woodcutter", "level": 9},
    {"building_type": "Clay Pit", "level": 9},
    {"building_type": "Iron Mine", "level": 9},
    {"building_type": "Woodcutter", "level": 10},
    {"building_type": "Clay Pit", "level": 10},
    {"building_type": "Iron Mine", "level": 10},
]
