build_list = [
    {"type": "resource", "land_type": "Woodcutter", "level": 2},
    {"type": "resource", "land_type": "Iron Mine", "level": 2},
    {"type": "resource", "land_type": "Clay Pit", "level": 2},
    {"type": "resource", "land_type": "Cropland", "level": 2},
    {"type": "building", "building_type": "Rally Point", "level": 1, "aid": 39},
    {"type": "building", "building_type": "Main Building", "level": 5},
    {"type": "building", "building_type": "Warehouse", "level": 3, "aid": 30},
    {"type": "building", "building_type": "Granary", "level": 3, "aid": 32},
    {"type": "building", "building_type": "Marketplace", "level": 1, "aid": 31},
    {"type": "building", "building_type": "Warehouse", "level": 6},
    {"type": "building", "building_type": "Barracks", "level": 1, "aid": 37},
    {"type": "building", "building_type": "Embassy", "level": 1, "aid": 29},
    {"type": "building", "building_type": "Warehouse", "level": 7},
    {"type": "building", "building_type": "Granary", "level": 5},
    {"type": "resource", "land_type": "Woodcutter", "level": 3},
    {"type": "resource", "land_type": "Iron Mine", "level": 3},
    {"type": "resource", "land_type": "Clay Pit", "level": 3},
    {"type": "resource", "land_type": "Cropland", "level": 3},
    {"type": "building", "building_type": "Main Building", "level": 15},
    {"type": "building", "building_type": "Barracks", "level": 5},
    {"type": "building", "building_type": "Academy", "level": 5, "aid": 36},
    {"type": "building", "building_type": "Smithy", "level": 3, "aid": 33},
    {"type": "building", "building_type": "Stable", "level": 3, "aid": 34},
    {"type": "building", "building_type": "Warehouse", "level": 13},
    {"type": "building", "building_type": "Granary", "level": 10},
    {"type": "building", "building_type": "Palisade", "level": 10, "aid": 40},
    {"type": "building", "building_type": "Marketplace", "level": 7},
    {"type": "resource", "land_type": "Cropland", "level": 5},
    {"type": "resource", "land_type": "Woodcutter", "level": 7},
    {"type": "resource", "land_type": "Iron Mine", "level": 7},
    {"type": "resource", "land_type": "Clay Pit", "level": 7},
    {"type": "building", "building_type": "Academy", "level": 10},
    {"type": "building", "building_type": "Smithy", "level": 10},
    {"type": "building", "building_type": "Stable", "level": 10},
    {"type": "building", "building_type": "Embassy", "level": 10},
    {"type": "building", "building_type": "Main Building", "level": 18},
    {"type": "building", "building_type": "Warehouse", "level": 18},
    {"type": "building", "building_type": "Granary ", "level": 16},
    {"type": "resource", "land_type": "Woodcutter", "level": 9},
    {"type": "resource", "land_type": "Iron Mine", "level": 9},
    {"type": "resource", "land_type": "Clay Pit", "level": 9},
    {"type": "resource", "land_type": "Cropland", "level": 9},
    {"type": "building", "building_type": "Marketplace", "level": 12},
    {"type": "building", "building_type": "Academy", "level": 15},
    {"type": "building", "building_type": "Smithy", "level": 15},
    {"type": "building", "building_type": "Stable", "level": 15},
    {"type": "building", "building_type": "Embassy", "level": 15},
    {"type": "building", "building_type": "Main Building", "level": 20},
    {"type": "building", "building_type": "Warehouse", "level": 20},
    {"type": "building", "building_type": "Granary ", "level": 20},
    {"type": "resource", "land_type": "Woodcutter", "level": 10},
    {"type": "resource", "land_type": "Iron Mine", "level": 10},
    {"type": "resource", "land_type": "Clay Pit", "level": 10},
    {"type": "resource", "land_type": "Cropland", "level": 10},
    {"type": "building", "building_type": "Marketplace", "level": 20},
    {"type": "building", "building_type": "Palisade", "level": 20},
]
