build_list = [
    {"type": "resource", "land_type": "Woodcutter", "level": 2},
    {"type": "resource", "land_type": "Iron Mine", "level": 2},
    {"type": "resource", "land_type": "Clay Pit", "level": 2},
    {"type": "resource", "land_type": "Cropland", "level": 2},
    {"type": "building", "building_type": "Rally Point", "level": 1, "aid": 39},
    {"type": "building", "building_type": "Main Building", "level": 5},
    {"type": "building", "building_type": "Warehouse", "level": 3, "aid": 30},
    {"type": "building", "building_type": "Granary", "level": 3, "aid": 32},
    {"type": "building", "building_type": "Warehouse", "level": 6},
    {"type": "building", "building_type": "Barracks", "level": 1, "aid": 37},
    {"type": "building", "building_type": "Cranny", "level": 1, "aid": 35},
    {"type": "building", "building_type": "Warehouse", "level": 7},
    {"type": "building", "building_type": "Granary", "level": 5},
    {"type": "resource", "land_type": "Woodcutter", "level": 3},
    {"type": "resource", "land_type": "Iron Mine", "level": 3},
    {"type": "resource", "land_type": "Clay Pit", "level": 3},
    {"type": "building", "building_type": "Barracks", "level": 5},
    {"type": "building", "building_type": "Academy", "level": 5, "aid": 36},
    {"type": "building", "building_type": "Smithy", "level": 3, "aid": 33},
    {"type": "building", "building_type": "Stable", "level": 3, "aid": 34},
    {"type": "building", "building_type": "Warehouse", "level": 13},
    {"type": "building", "building_type": "Granary ", "level": 10},
    {"type": "resource", "land_type": "Cropland", "level": 5},
    {"type": "resource", "land_type": "Woodcutter", "level": 7},
    {"type": "resource", "land_type": "Iron Mine", "level": 7},
    {"type": "resource", "land_type": "Clay Pit", "level": 7},
]
